"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Search, Filter, FileText } from "lucide-react";
import { BriefingCard } from "@/components/briefings/BriefingCard";
import { Badge } from "@/components/ui/badge";
import { mockBriefings } from "@/lib/mock-data";
import type { Priority } from "@/lib/types";

const priorities: { label: string; value: Priority | "all" }[] = [
  { label: "All", value: "all" },
  { label: "Critical", value: "critical" },
  { label: "High", value: "high" },
  { label: "Medium", value: "medium" },
  { label: "Low", value: "low" },
];

export default function BriefingsPage() {
  const [search, setSearch] = useState("");
  const [priority, setPriority] = useState<Priority | "all">("all");
  const [slackOnly, setSlackOnly] = useState(false);

  const filtered = mockBriefings.filter((b) => {
    if (search && !b.title.toLowerCase().includes(search.toLowerCase())) return false;
    if (priority !== "all" && b.priority !== priority) return false;
    if (slackOnly && !b.sentToSlack) return false;
    return true;
  });

  return (
    <div className="relative min-h-screen">
      <div className="fixed inset-0 grid-bg pointer-events-none opacity-40" />

      <div className="relative px-8 py-8 space-y-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-start justify-between"
        >
          <div>
            <div className="flex items-center gap-2 mb-1">
              <FileText className="w-5 h-5 text-brand-400" />
              <h1 className="text-2xl font-bold text-zinc-100">Intelligence Briefings</h1>
            </div>
            <p className="text-zinc-500 text-sm">
              Executive-grade competitive intelligence reports generated by autonomous AI agents.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant="info">{filtered.length} briefings</Badge>
          </div>
        </motion.div>

        {/* Filters */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="glass rounded-xl border border-zinc-800/60 p-4 flex flex-wrap items-center gap-4"
        >
          {/* Search */}
          <div className="relative flex-1 min-w-48">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-zinc-500" />
            <input
              type="text"
              placeholder="Search briefings..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full bg-zinc-900/60 border border-zinc-800 rounded-lg pl-9 pr-4 py-2 text-sm text-zinc-300 placeholder:text-zinc-600 focus:outline-none focus:border-brand-500/50 transition-all"
            />
          </div>

          {/* Priority filter */}
          <div className="flex items-center gap-1.5">
            <Filter className="w-3.5 h-3.5 text-zinc-500" />
            <div className="flex gap-1">
              {priorities.map((p) => (
                <button
                  key={p.value}
                  onClick={() => setPriority(p.value)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                    priority === p.value
                      ? "bg-brand-500/20 text-brand-400 border border-brand-500/30"
                      : "text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800/50"
                  }`}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </div>

          {/* Slack filter */}
          <button
            onClick={() => setSlackOnly(!slackOnly)}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
              slackOnly
                ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                : "text-zinc-500 hover:text-zinc-300 bg-zinc-800/30 border border-zinc-700/30"
            }`}
          >
            Slack delivered only
          </button>
        </motion.div>

        {/* Briefing cards */}
        <div className="space-y-4">
          {filtered.length === 0 ? (
            <div className="glass rounded-xl border border-zinc-800/60 p-12 text-center">
              <FileText className="w-8 h-8 text-zinc-700 mx-auto mb-3" />
              <p className="text-zinc-500 text-sm">No briefings match your filters.</p>
            </div>
          ) : (
            filtered.map((briefing, i) => (
              <motion.div
                key={briefing.id}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.06 }}
              >
                <BriefingCard briefing={briefing} />
              </motion.div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
